/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_apotek;

import java.sql.*;
import Connection.Koneksi;
import Login.Login_apotek;
import Login.Registrasi_Admin;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Menu_utama extends javax.swing.JFrame {
    private Connection conn = new Koneksi().connect();
    public static String nama;
    

    public Menu_utama() {
        initComponents();
        txtnmlngkp.setText(Registrasi_Admin.getnama());
        String KD = UserID.getUserLogin();
        txtnmlngkp.setText(KD);    
        JumlahPasien();
        JumlahApoteker();
        JumlahDokter();
        JumlahObat();
        JumlahAdmin();
    }
    
    public int JumlahPasien(){
        int count = 0;
        try{
            String SQL = "select * from tb_pasien";
            Statement State = conn.createStatement();
            ResultSet Result = State.executeQuery(SQL);
            while (Result.next()) {
                count++;
            }  
            txtdataPasien.setText(Integer.toString(count));
        }catch(SQLException e){
            
        }
        return count;
    }    

    public int JumlahApoteker(){
        int count = 0;
        try{
            String SQL = "select * from tb_apoteker";
            Statement State = conn.createStatement();
            ResultSet Result = State.executeQuery(SQL);
            while (Result.next()) {
                count++;
            }  
            txtdataApoteker.setText(Integer.toString(count));
        }catch(SQLException e){
            
        }
        return count;
    }    

    public int JumlahObat(){
        int count = 0;
        try{
            String SQL = "select * from tb_obat";
            Statement State = conn.createStatement();
            ResultSet Result = State.executeQuery(SQL);
            while (Result.next()) {
                count++;
            }  
            txtdataObat.setText(Integer.toString(count));
        }catch(SQLException e){
            
        }
        return count;
    }    

    public int JumlahDokter(){
        int count = 0;
        try{
            String SQL = "select * from tb_dokter";
            Statement State = conn.createStatement();
            ResultSet Result = State.executeQuery(SQL);
            while (Result.next()) {
                count++;
            }  
            txtdataDokter.setText(Integer.toString(count));
        }catch(SQLException e){
            
        }
        return count;
    }    

    public int JumlahAdmin(){
        int count = 0;
        try{
            String SQL = "select * from tb_admin";
            Statement State = conn.createStatement();
            ResultSet Result = State.executeQuery(SQL);
            while (Result.next()) {
                count++;
            }  
            txtdataAdmin.setText(Integer.toString(count));
        }catch(SQLException e){
            
        }
        return count;
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtdataAdmin = new javax.swing.JLabel();
        txtdataDokter = new javax.swing.JLabel();
        txtdataObat = new javax.swing.JLabel();
        txtdataApoteker = new javax.swing.JLabel();
        txtdataPasien = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnmlngkp = new javax.swing.JLabel();
        bpemesananObat = new javax.swing.JButton();
        bkonsul = new javax.swing.JButton();
        Icon_pesan = new javax.swing.JLabel();
        text_Konsultasi = new javax.swing.JLabel();
        Icon_Konsultasi = new javax.swing.JLabel();
        text_pesanObat = new javax.swing.JLabel();
        bdataObat = new javax.swing.JButton();
        text_dataObat = new javax.swing.JLabel();
        icon_dataObat = new javax.swing.JLabel();
        bdataPasien = new javax.swing.JButton();
        text_dataPasien = new javax.swing.JLabel();
        icon_dataPasien = new javax.swing.JLabel();
        bdataApoteker = new javax.swing.JButton();
        text_dataApoteker = new javax.swing.JLabel();
        icon_apoteker = new javax.swing.JLabel();
        bdataAdmin = new javax.swing.JButton();
        text_dataAdmin = new javax.swing.JLabel();
        icon_dataAdmin = new javax.swing.JLabel();
        bdataDokter = new javax.swing.JButton();
        text_dataDokter = new javax.swing.JLabel();
        icon_dokter = new javax.swing.JLabel();
        bcetakLaporan = new javax.swing.JButton();
        text_cetakLaporan = new javax.swing.JLabel();
        icon_laporan = new javax.swing.JLabel();
        bdataJadwal = new javax.swing.JButton();
        text_dataJadwal = new javax.swing.JLabel();
        icon_jadwalPraktek = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdataAdmin.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdataAdmin.setText("Data");
        jPanel2.add(txtdataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        txtdataDokter.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdataDokter.setText("Data");
        jPanel2.add(txtdataDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        txtdataObat.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdataObat.setText("Data");
        jPanel2.add(txtdataObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        txtdataApoteker.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdataApoteker.setText("Data");
        jPanel2.add(txtdataApoteker, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        txtdataPasien.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdataPasien.setText("Data");
        jPanel2.add(txtdataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sick_35px.png"))); // NOI18N
        jLabel14.setText("Data Admin");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sick_35px.png"))); // NOI18N
        jLabel10.setText("Data Dokter");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sick_35px.png"))); // NOI18N
        jLabel11.setText("Data Obat");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sick_35px.png"))); // NOI18N
        jLabel12.setText("Data Pasien");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sick_35px.png"))); // NOI18N
        jLabel13.setText("Data Apoteker");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        bkeluar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit_30px.png"))); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 260, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo Apoteker.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 280, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rectangle 30.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rectangle 30.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rectangle 30.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rectangle 30.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rectangle 30.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 510));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("APOTEK YEKA FARMA21 ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 510, 20));

        txtnmlngkp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtnmlngkp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtnmlngkp.setText("Nama Pengguna");
        txtnmlngkp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtnmlngkp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 250, 20));

        bpemesananObat.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bpemesananObat.setBorder(null);
        bpemesananObat.setBorderPainted(false);
        bpemesananObat.setContentAreaFilled(false);
        bpemesananObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpemesananObat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bpemesananObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpemesananObatActionPerformed(evt);
            }
        });
        jPanel1.add(bpemesananObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 130, 110));

        bkonsul.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bkonsul.setBorder(null);
        bkonsul.setBorderPainted(false);
        bkonsul.setContentAreaFilled(false);
        bkonsul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkonsul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkonsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkonsulActionPerformed(evt);
            }
        });
        jPanel1.add(bkonsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 130, 110));

        Icon_pesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pills_70px.png"))); // NOI18N
        jPanel1.add(Icon_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 70, 60));

        text_Konsultasi.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_Konsultasi.setText("Konsultasi");
        jPanel1.add(text_Konsultasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 320, -1, 20));

        Icon_Konsultasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/doctors_bag_70px.png"))); // NOI18N
        jPanel1.add(Icon_Konsultasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 70, 60));

        text_pesanObat.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_pesanObat.setText("Pemesanan Obat");
        jPanel1.add(text_pesanObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, 20));

        bdataObat.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bdataObat.setBorder(null);
        bdataObat.setBorderPainted(false);
        bdataObat.setContentAreaFilled(false);
        bdataObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdataObat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataObatActionPerformed(evt);
            }
        });
        jPanel1.add(bdataObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 130, 110));

        text_dataObat.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_dataObat.setText("Data Obat");
        jPanel1.add(text_dataObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, 20));

        icon_dataObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pillsData_70px.png"))); // NOI18N
        jPanel1.add(icon_dataObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 70, 60));

        bdataPasien.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bdataPasien.setBorder(null);
        bdataPasien.setBorderPainted(false);
        bdataPasien.setContentAreaFilled(false);
        bdataPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdataPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdataPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataPasienActionPerformed(evt);
            }
        });
        jPanel1.add(bdataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 130, 110));

        text_dataPasien.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_dataPasien.setText("Data Pasien");
        jPanel1.add(text_dataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, 20));

        icon_dataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sick_70px.png"))); // NOI18N
        jPanel1.add(icon_dataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 70, 60));

        bdataApoteker.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bdataApoteker.setBorder(null);
        bdataApoteker.setBorderPainted(false);
        bdataApoteker.setContentAreaFilled(false);
        bdataApoteker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdataApoteker.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdataApoteker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataApotekerActionPerformed(evt);
            }
        });
        jPanel1.add(bdataApoteker, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 130, 110));

        text_dataApoteker.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_dataApoteker.setText("Data Apoteker");
        jPanel1.add(text_dataApoteker, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, 20));

        icon_apoteker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/doctor_female_70px.png"))); // NOI18N
        jPanel1.add(icon_apoteker, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 70, 60));

        bdataAdmin.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bdataAdmin.setBorder(null);
        bdataAdmin.setBorderPainted(false);
        bdataAdmin.setContentAreaFilled(false);
        bdataAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdataAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataAdminActionPerformed(evt);
            }
        });
        jPanel1.add(bdataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 130, 110));

        text_dataAdmin.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_dataAdmin.setText("Data Admin");
        jPanel1.add(text_dataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, 20));

        icon_dataAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_70px.png"))); // NOI18N
        jPanel1.add(icon_dataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 70, 60));

        bdataDokter.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bdataDokter.setBorder(null);
        bdataDokter.setBorderPainted(false);
        bdataDokter.setContentAreaFilled(false);
        bdataDokter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdataDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdataDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataDokterActionPerformed(evt);
            }
        });
        jPanel1.add(bdataDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 130, 110));

        text_dataDokter.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_dataDokter.setText("Data Dokter");
        jPanel1.add(text_dataDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, 20));

        icon_dokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/doctor_male_70px.png"))); // NOI18N
        jPanel1.add(icon_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 70, 60));

        bcetakLaporan.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bcetakLaporan.setBorder(null);
        bcetakLaporan.setBorderPainted(false);
        bcetakLaporan.setContentAreaFilled(false);
        bcetakLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcetakLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bcetakLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakLaporanActionPerformed(evt);
            }
        });
        jPanel1.add(bcetakLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 130, 110));

        text_cetakLaporan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_cetakLaporan.setText("Laporan");
        jPanel1.add(text_cetakLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, 20));

        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/print_70px.png"))); // NOI18N
        jPanel1.add(icon_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 70, 60));

        bdataJadwal.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bdataJadwal.setBorder(null);
        bdataJadwal.setBorderPainted(false);
        bdataJadwal.setContentAreaFilled(false);
        bdataJadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdataJadwal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdataJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataJadwalActionPerformed(evt);
            }
        });
        jPanel1.add(bdataJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 130, 110));

        text_dataJadwal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        text_dataJadwal.setText("Jadwal Praktek");
        jPanel1.add(text_dataJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 460, -1, 20));

        icon_jadwalPraktek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/schedule_70px.png"))); // NOI18N
        jPanel1.add(icon_jadwalPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 70, 60));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jl. Komodor Udara No. 30 Halim Perdanakusumah Telp: (021) 9401 4542");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 510, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 510));

        setSize(new java.awt.Dimension(809, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bkonsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkonsulActionPerformed
        form_konsultasiDokter konsul;
        konsul = new form_konsultasiDokter();
        konsul.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bkonsulActionPerformed

    private void bpemesananObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpemesananObatActionPerformed
        form_pemesananObat pesan;
        pesan = new form_pemesananObat();
        pesan.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bpemesananObatActionPerformed

    private void bdataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataObatActionPerformed
        form_dataObat obat;
        obat = new form_dataObat();
        obat.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bdataObatActionPerformed

    private void bdataPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataPasienActionPerformed
        form_dataPasien pasien;
        pasien = new form_dataPasien();
        pasien.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bdataPasienActionPerformed

    private void bdataApotekerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataApotekerActionPerformed
        form_dataApoteker apoteker;
        apoteker = new form_dataApoteker();
        apoteker.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bdataApotekerActionPerformed

    private void bdataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataAdminActionPerformed
        form_dataAdmin admin;
        admin = new form_dataAdmin();
        admin.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bdataAdminActionPerformed

    private void bdataDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataDokterActionPerformed
        form_dataDokter dokter;
        dokter = new form_dataDokter();
        dokter.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bdataDokterActionPerformed

    private void bcetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakLaporanActionPerformed
        form_cetakLaporan laporan;
        laporan = new form_cetakLaporan();
        laporan.setVisible(true);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_bcetakLaporanActionPerformed

    private void bdataJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataJadwalActionPerformed
        form_dataJadwal jadwal;
        jadwal = new form_dataJadwal();
        jadwal.setVisible(true);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_bdataJadwalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        int tny = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar ?","Tanya",JOptionPane.YES_NO_OPTION);
        if (tny==0) {     
            try {
                dispose();
                dispose();
            } catch (Exception e) {
            }
        }
        new Login.Login_apotek().setVisible(true);
    }//GEN-LAST:event_bkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon_Konsultasi;
    private javax.swing.JLabel Icon_pesan;
    private javax.swing.JButton bcetakLaporan;
    private javax.swing.JButton bdataAdmin;
    private javax.swing.JButton bdataApoteker;
    private javax.swing.JButton bdataDokter;
    private javax.swing.JButton bdataJadwal;
    private javax.swing.JButton bdataObat;
    private javax.swing.JButton bdataPasien;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bkonsul;
    private javax.swing.JButton bpemesananObat;
    private javax.swing.JLabel icon_apoteker;
    private javax.swing.JLabel icon_dataAdmin;
    private javax.swing.JLabel icon_dataObat;
    private javax.swing.JLabel icon_dataPasien;
    private javax.swing.JLabel icon_dokter;
    private javax.swing.JLabel icon_jadwalPraktek;
    private javax.swing.JLabel icon_laporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel text_Konsultasi;
    private javax.swing.JLabel text_cetakLaporan;
    private javax.swing.JLabel text_dataAdmin;
    private javax.swing.JLabel text_dataApoteker;
    private javax.swing.JLabel text_dataDokter;
    private javax.swing.JLabel text_dataJadwal;
    private javax.swing.JLabel text_dataObat;
    private javax.swing.JLabel text_dataPasien;
    private javax.swing.JLabel text_pesanObat;
    private javax.swing.JLabel txtdataAdmin;
    private javax.swing.JLabel txtdataApoteker;
    private javax.swing.JLabel txtdataDokter;
    private javax.swing.JLabel txtdataObat;
    private javax.swing.JLabel txtdataPasien;
    private javax.swing.JLabel txtnmlngkp;
    // End of variables declaration//GEN-END:variables
}
