
package Login;

import java.sql.*;
import Connection.Koneksi;
import Menu_apotek.UserID;
import javax.swing.JOptionPane;


public class Login_apotek extends javax.swing.JFrame {
    private Connection conn = new Koneksi().connect();
    public static String user;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Login_apotek
     */
    public Login_apotek() {
        initComponents();
        
    }

    public static String getusername(){
        return user;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bkeluar = new javax.swing.JButton();
        bloginApp = new javax.swing.JButton();
        bregistrasi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        blogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bkeluar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit_50px.png"))); // NOI18N
        bkeluar.setText("  Keluar");
        bkeluar.setBorder(null);
        bkeluar.setBorderPainted(false);
        bkeluar.setContentAreaFilled(false);
        bkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 50));

        bloginApp.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bloginApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login_50px.png"))); // NOI18N
        bloginApp.setText("  Login");
        bloginApp.setBorder(null);
        bloginApp.setBorderPainted(false);
        bloginApp.setContentAreaFilled(false);
        bloginApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bloginApp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bloginApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginAppActionPerformed(evt);
            }
        });
        jPanel2.add(bloginApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 50));

        bregistrasi.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bregistrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/registration_50px.png"))); // NOI18N
        bregistrasi.setText("  Registrasi");
        bregistrasi.setBorder(null);
        bregistrasi.setBorderPainted(false);
        bregistrasi.setContentAreaFilled(false);
        bregistrasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bregistrasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bregistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregistrasiActionPerformed(evt);
            }
        });
        jPanel2.add(bregistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo Apoteker.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 380));

        txtusername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 300, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/password_30px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_30px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 300, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELAMAT DATANG");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 470, 20));

        blogin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        blogin.setText("LOGIN");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel1.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 120, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 380));

        setSize(new java.awt.Dimension(704, 419));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
       int tny = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar ?","Tanya",JOptionPane.YES_NO_OPTION);
        if (tny==0) {     
            try {
                System.exit(0);
            } catch (Exception e) {
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bloginAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloginAppActionPerformed

    private void bregistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregistrasiActionPerformed
        dispose();
        Registrasi_Admin regist;
        regist = new Registrasi_Admin();
        regist.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bregistrasiActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        try{
            String username = txtusername.getText();
            String pass= String.valueOf(txtpass.getPassword());
            String SQL = "Select * from tb_admin where username='" +username+"' and password='"+pass+"'";
            PreparedStatement state = conn.prepareStatement(SQL);
            ResultSet Result = state.executeQuery(SQL);
            if(Result.next()){
                UserID.setUserLogin(Result.getString("nama_admin"));
                if(txtusername.getText().equals(Result.getString("username"))&&
                        String.valueOf(txtpass.getPassword()).equals(Result.getString("password"))){
                    user = Result.getString("username");
                    JOptionPane.showMessageDialog(this, "Selamat Datang \n Sistem Informasi Apoteker \n Yeka Farma21");
                    
                }
                dispose();
                new Menu_apotek.Menu_utama().setVisible(true);
            }else{
                    JOptionPane.showMessageDialog(null, "Login Gagal!");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Username/Password Salah "+e);
        }
      // TODO add your handling code here:
    }//GEN-LAST:event_bloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_apotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton blogin;
    private javax.swing.JButton bloginApp;
    private javax.swing.JButton bregistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
