/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.*;
import Connection.Koneksi;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Registrasi_Admin extends javax.swing.JFrame {
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel UserTab;
    public static String nama;
    String usrnm;

    public Registrasi_Admin() {
        initComponents();
        clear();
        aktif();   
        UserModelTable();
    }
    
    protected void aktif (){
        txtusername.requestFocus();
        //cbprodi.setSelectedItem(null);
    }
    
    public static String getnama(){
        return nama;
    }
    
    public void clear(){
        txtnmAdmin.setText("");
        cbjenkel.setSelectedItem(null);
        txtalamat.setText("");
        txtnotelp.setText("");
        txtusername.setText("");
        txtpassword.setText("");
    }    

    public void UserModelTable(){
        
        String nama = txtnmAdmin.getText();
        //String cari = txtcari.getText();
        Object [] Row ={"Nama","Jenis Kelamin","Alamat","No. Telepon","Username", "Password"};
        UserTab = new DefaultTableModel(null, Row);
        try{
            String sql = "SELECT * FROM tb_admin";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                UserTab.addRow(new Object[]{
                    
                    rs.getString(1), 
                    rs.getString(2), 
                    rs.getString(3), 
                    rs.getString(4), 
                    rs.getString(5), 
                    rs.getString(6)});     
                }
                //tbuser.setModel(UserTab);
            }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "data gagal dipanggil "+ex);
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bkeluar = new javax.swing.JButton();
        bloginApp = new javax.swing.JButton();
        bregistrasi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnmAdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnotelp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bbatal = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        cbjenkel = new javax.swing.JComboBox<>();
        txtpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bkeluar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit_50px.png"))); // NOI18N
        bkeluar.setText("  Keluar");
        bkeluar.setBorder(null);
        bkeluar.setBorderPainted(false);
        bkeluar.setContentAreaFilled(false);
        bkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 50));

        bloginApp.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bloginApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login_50px.png"))); // NOI18N
        bloginApp.setText("  Login");
        bloginApp.setBorder(null);
        bloginApp.setBorderPainted(false);
        bloginApp.setContentAreaFilled(false);
        bloginApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bloginApp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bloginApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginAppActionPerformed(evt);
            }
        });
        jPanel2.add(bloginApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 50));

        bregistrasi.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bregistrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/registration_50px.png"))); // NOI18N
        bregistrasi.setText("  Registrasi");
        bregistrasi.setBorder(null);
        bregistrasi.setBorderPainted(false);
        bregistrasi.setContentAreaFilled(false);
        bregistrasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bregistrasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bregistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregistrasiActionPerformed(evt);
            }
        });
        jPanel2.add(bregistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo Apoteker.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 380));

        txtnmAdmin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtnmAdmin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtnmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmAdminActionPerformed(evt);
            }
        });
        jPanel1.add(txtnmAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 350, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Nama Admin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/name_30px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gender_30px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 20));

        txtalamat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtalamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 350, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/address_30px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("No. Telepon");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, 20));

        txtnotelp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtnotelp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotelpActionPerformed(evt);
            }
        });
        jPanel1.add(txtnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 350, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phone_30px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_30px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("Username");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, 20));

        txtusername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 350, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Password");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/password_30px.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        bbatal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 100, 30));

        bsimpan.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, 30));

        cbjenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jPanel1.add(cbjenkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 350, -1));

        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 350, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 380));

        setSize(new java.awt.Dimension(705, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
       int tny = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar ?","Tanya",JOptionPane.YES_NO_OPTION);
        if (tny==0) {     
            try {
                System.exit(0);
            } catch (Exception e) {
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bloginAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginAppActionPerformed
        dispose();
        Login_apotek login;
        login = new Login_apotek();
        login.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bloginAppActionPerformed

    private void bregistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregistrasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bregistrasiActionPerformed

    private void txtnmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmAdminActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void txtnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotelpActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "insert into tb_admin values (?,?,?,?,?,?)";
        try{
            PreparedStatement st = conn.prepareStatement(sql);
            
            st.setString(1, txtnmAdmin.getText());
            st.setString(2, cbjenkel.getItemAt(cbjenkel.getSelectedIndex()));
            st.setString(3, txtalamat.getText());
            st.setString(4, txtnotelp.getText());
            st.setString(5, txtusername.getText());
            st.setString(6, String.valueOf(txtpassword.getPassword()));            
       
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            clear();
            txtusername.requestFocus();
            
            
            }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Data gagal Disimpan " +ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_bbatalActionPerformed

    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
        usrnm=txtusername.getText();
        int ascii = evt.getKeyCode();
        if(ascii==10){
            try {
                String sql="select * from tb_admin where username='"+ usrnm +"'";
                Statement st=conn.createStatement();
                ResultSet rsusrnm = st.executeQuery(sql);
                while (rsusrnm.next()){
                    txtnmAdmin.setText(rsusrnm.getString(1));
                    cbjenkel.setSelectedItem(rsusrnm.getString(2));
                    txtalamat.setText(rsusrnm.getString(3));
                    txtnotelp.setText(rsusrnm.getString(4));
                    txtpassword.setText(rsusrnm.getString(6));
                    //bdelete.enable(true);
                    //bedit.enable(true);

                }
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, "Data Tidak Di Temukan ....!! \n"
                    +e.getMessage());
                txtusername.requestFocus();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bloginApp;
    private javax.swing.JButton bregistrasi;
    private javax.swing.JButton bsimpan;
    private javax.swing.JComboBox<String> cbjenkel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnmAdmin;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
